// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFBd0bqpHLUp0OdnCcWmxMqi2a79YeKmc',
    appId: '1:704115722197:web:720cb34c798cc746dddf5c',
    messagingSenderId: '704115722197',
    projectId: 'proyecto-21bae',
    authDomain: 'proyecto-21bae.firebaseapp.com',
    storageBucket: 'proyecto-21bae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBcBnIvj4SpyppfPal_9pjyKOD8wXwMM0',
    appId: '1:704115722197:android:cb2153f79292c2d6dddf5c',
    messagingSenderId: '704115722197',
    projectId: 'proyecto-21bae',
    storageBucket: 'proyecto-21bae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC57Aph8sdV5bXoTSxQIBzLfaSLE2SDYzI',
    appId: '1:704115722197:ios:2af57b5b91fb19f8dddf5c',
    messagingSenderId: '704115722197',
    projectId: 'proyecto-21bae',
    storageBucket: 'proyecto-21bae.firebasestorage.app',
    iosBundleId: 'com.example.idea1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC57Aph8sdV5bXoTSxQIBzLfaSLE2SDYzI',
    appId: '1:704115722197:ios:2af57b5b91fb19f8dddf5c',
    messagingSenderId: '704115722197',
    projectId: 'proyecto-21bae',
    storageBucket: 'proyecto-21bae.firebasestorage.app',
    iosBundleId: 'com.example.idea1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFBd0bqpHLUp0OdnCcWmxMqi2a79YeKmc',
    appId: '1:704115722197:web:ecbaf8b5fc9c6443dddf5c',
    messagingSenderId: '704115722197',
    projectId: 'proyecto-21bae',
    authDomain: 'proyecto-21bae.firebaseapp.com',
    storageBucket: 'proyecto-21bae.firebasestorage.app',
  );
}
